//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotes
    {
        public int notId { get; set; }
        public Nullable<int> student { get; set; }
        public Nullable<int> lecture { get; set; }
        public Nullable<short> exam1 { get; set; }
        public Nullable<short> exam2 { get; set; }
        public Nullable<short> exam3 { get; set; }
        public Nullable<double> average { get; set; }
        public Nullable<bool> state { get; set; }
    
        public virtual tblLectures tblLectures { get; set; }
        public virtual tblStudents tblStudents { get; set; }
    }
}
