//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNote
    {
        public int id { get; set; }
        public Nullable<int> lesson { get; set; }
        public Nullable<int> student { get; set; }
        public Nullable<short> exam1 { get; set; }
        public Nullable<short> exam2 { get; set; }
        public Nullable<double> average { get; set; }
        public Nullable<bool> state { get; set; }
    
        public virtual tblLesson tblLesson { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
